#!/bin/bash


echo " Pleas writ one number: "

read -a numbers
largest=${numbers[0]}
smallest=${numbers[0]}
for num in ${numbers[@]}
do
 if [[ $num -gt $largest ]]
  then
    largest=$num
  fi
  if [[ $num -lt $smallest ]]
  then
    smallest=$num
  fi
done


echo "The largest number is $largest"
echo "The smallest number is $smallest"

